

applications:
- api_domain: https://platform.staging.jit.io/
  application_name: zap-stg-api
  auth_header_name: Authorization
  auth_header_value: encrypted$AQICAHhpFcIXIhU6d93x5dEW8mdH+GAoJET0G2RkVqkI5vH/4QGIrpwiS/jwqmSgf780UDtcAAAE/TCCBPkGCSqGSIb3DQEHBqCCBOowggTmAgEAMIIE3wYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAwqNyHMQmmqgDhJK6wCARCAggSwfab3HDFPU3NPXrtucvwZAzrD0FcxxL6C7xYt9MIE/xXfXn94w3mmNNuHdEIpt3ZgcW5aH814FcS3xtZ1Uu6zAg7pHhT3UJ13ypu4YZg67mtSS0f1kutTQ94mFJRh/CThKP9hJzcUB96GHLjXnPhB8caJUwUMLGm2+hyfEkwKpQu3FCR8a6GRZqKec+QDRAq1IcE3hGlpHfdu/ChCoBDEsGfjEle0mI81wrFPT8tMbpJjTc60+/BRmXOpgcIWNItuyBUs8Vlur1buka+1MWETdf5luCsRugWFO5le+SD3mEMEGVa2c4uu3vQCXx2cpJfV9TfDXK4Wy7+UuliBIIS4bSsffS9hdsoHt+VueLT1S0+FlVit5tUAGX1v42qvIo1KeK1iuTd1VlJ9zzi2m6DcvNGdPRazBeF20wc3sTAYWrloyADe12SYHCCROPpECzdUzThfKEWyEFWHh7XCXncC4ww6UfrGExgkbxyrpxf6wp8QIze3C9LGiGkLKDjV7q3mcuiKTkr1TYgJOguvlJPECunPrtNozpDtBY6OrOufNw8ezfV3lg9/1edgW4qXYO8jGnhIcC9ItGa7hBovYIkc+BGEEHH95i7Q/qxmnNIfCMAakCFACyGPuYa3M6z2+1ImlUi1e8UU/uUpA+lQtsOD0raWJH9zE4GZTPtQUFAZt9o0p9Uq+TPFN9xZ30M/v0R6Xgx84im2538kbF819kmUppmBoLaO/NbrZbXjsmgQcz71oAk4eqKxDMtrOzNuOrsxsh70yHUwihlPS7Li3KUxKdGhen8qBAEnxKfi4qAw045ndfoU51ffQTLgTTXUuQxDrQPQm5K6CV/Ck9tEt14WLmL6JADvVtFOEmcpoAkE0bwZLII8mQ2guYT43AAHkVoeah/c0BGlq7pwGIm/LTspRp7d9eDXfWI2Pg4gsb4FPL6CgIOLddexVoBek2bsZn527sBCWBeO9nom4Xj290gmlFAvQ41eiIzbicskevic0yWUNHB5khgyJQc9k0WXr+rWkkLgii7/X7/BViI21lRh9bYHgZDMp7ynDWlxbKsinQd8e8A/dp2pQ5Dky/zrq6eP/Y8gw4tYkrkuvPjD8ON8Oj217cRIx+AMO5zJTaLvHSYiR7ahJkVsz7ApppeUtSOVGN5N5nx9XlcEa3Trwml5NoLMkxcJTS0YVm0RNinPZ39FBbjDz90YuLGxfCL74+vHr83IZOCmjCtIyWSpirvzbIAlezpLlRO3snPQsaGgiGw55SoTg+GjArjsdOiYYuaa9WRGCpyOfooSnyIo1SeBIrAOqrPDRC0PKWNfSouE/Y6a/GU0GWjUILqSoEruA6ItayqzvzBTusHZ2vGAskkr0UWLg6S0KLiL22n+tD9ZJGYPc1nEKr0kWvZcAMSu1uvgn/iK/dT8vJJLBXgDeVOM6ziAmAbLRrJdGFdEKoPx8AHYoBG/NHwCKynFUBaDjOVRXiPFX7dvJ8OcIRFX34hDEPnLP8WkredcqrJjGFYs6cT6DuRH6L6Z8oCCK1xUzK0FtvFCuAA2ezmadTKGx7nuGB3DuJrDVibwnJEMqXPzCUDxVr6NstVDDhAVhbCjbdSY
  authentication_mode: header-bearer
  exclude_paths: []
  target_url: https://meshi-bucket.s3.amazonaws.com/openapi.json
  type: api
- api_domain: https://platform.staging.jit.io/
  application_name: zap-stg-web
  auth_header_name: Authorization
  auth_header_value: encrypted$AQICAHhpFcIXIhU6d93x5dEW8mdH+GAoJET0G2RkVqkI5vH/4QHDKDPi6IRMdG3PGLJuIVOOAAAE/TCCBPkGCSqGSIb3DQEHBqCCBOowggTmAgEAMIIE3wYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAwmyfjxQcN0s0XCLHMCARCAggSwPz0SIRTy253GTPn7ipycrCCyLEMxC32ka9jDTSYiQgD2kHKEqcVRT6d0NZJKIuLOOxORmkqhogDeudJCUMrw+46YafhFA92O/5dxIApq2+w4cqd5YsXENVqI9d3T0FLoeTEaFpMp7eF+ORgIT7UGSsZP90JOt4Gilsm1xIC/Fkp1Z5NKQI5Pk5Rsq0hV3iK23pBDuCwvK2jRnp87v924Jpb2xjhEALisDCPrht3uLr5o4g/OJID7f53JT2X1saOTk02SVWWDFZVJSIq5OnrXINH2fFfOjnpUTk5rqhh8P3k8n8ZURUia8sk7LGKUZpsrWKSSk84ftOORz1Xu/Xo7ZBSw7g8T2ceUf/bkegbip2PW0N2gghYxCAvwRdjxBda6Ls7qd4XmShlYw8I+8Q5rj7RcIfii0ilUh+Pa9WUzuwddMK5+A8lByyz6eBVzNMRVv4FI60DfblW5G03g8XmiZR5Ii1/I9/O388ApurxyrnPZe+rHGkrPF8dpstMqQ1nfOzavyuHbs0PqJlItIDPrAvLwvVvElwGkxsi2P9H/6DPtFiJH5PUVzCNZURA8A2Z3ALCn9YdAbH3PDsPiLBv4ghtCkU687+iezyo+rDywXIpugq6uNMzE97Fm957QSRWbc+ssOfRU0BbZy6jz1hq5twsuisDHbyUc9H96LLjL6XpQ4Q1dWg0PBw7pyaU3iIF0IRDq3bqt7OpZwYbW7auIJ91p7y0kJIJt5QU/R4Upk04bewI8E2U3KdrCZzYVANW/+akTDk8xIGVxSyCDW//3+IQ1WELYyJx8HT5ojGfDSrNKMIGCHVIVdxe+oRR2TPJWpRSECqHUwfCBGX4vPFvXrrwcV0rO2tS0+gh/o4jUNX2RVtOvc1u3X19KNBQkS3tb2qGuIfcj0OGhpr/Th0UfdGrJNCzpMyATRT4uc09rjHBXsXuLHNiRbAGp9AmxXwZ2pMjhyGUa8h4vX9ek2koQEtQWW59s3Z1aJlooC2/7jqXDirbN/mLPvMTHbwqUrgNjV3XOiW3UPjGHjn/nUE8ZTJb+Re/xEZlpeNuuOFZKUxhEJKDgyJ3OoirCn+kg/yBfGtgZvOXYih3LeGzkTd39APN8zQ+kDNFLM3fWwXVBvNHoJdcqlTnDERuWMDJpoeIQ1Pe2o+h4tl3OeoPWTEEh972wZhu7EWDVL3lRPphAFEZUdeiSbjdIBO/E3UGBaQ1MkVljwVkTq8sIUGQ8UB0BK63c0Akp1yp1rVM61T59fpseDmOa4W07MFrtxEcgIeJmV2ZC3j3Kjl2bNswG6HVQjMLD9X7sDrBmKhDvQIyO7y/fLRfMTycV3fsnwRdtOsq0OC70cPd33QWGZi6LAABr6GIUyBEjGEjNbhsmFSv210EV0gmvpYUhq33sOErLuu/gQAB9Nf6SFrFvKz028A6RVOLh2sye9/acCBOqu3CbHpYEVQmTb4RhBrVFDXKbICqiS/iG+baig99M15ID+uiyDkF2RdZcnd9etiNV2RSW3GZFyjAq/c7RLkqWhB0lqaPYfd8s5tsO0xc/WEdVs7qPZVY7xg7uu7ovNwAiEMNE4KZm4PYxUQSoRaSI6NiCjWTj
  authentication_mode: header-bearer
  exclude_paths: []
  target_url: https://platform.staging.jit.io/
  type: web
- application_name: 'prowler-staging'
  type: aws_configuration
  account_ids:
    - 053588668385
plan_items:
  item-runtime-misconfiguration-detection:
    my-staging:
      tags:
      - 'staging'
      configuration:
      - 'prowler-staging'
      trigger: 'deployment'
aws:
- account_id: 053588668385
  account_name: 'AccountThree'
  deploy_region: us-east-1
  regions:
  - us-east-1
  type: account
deployment:
  environments:
  - staging
