applications:
- api_domain: api.staging.jit.io
  application_name: zap-stg
  authentication_key: Authorization
  authentication_mode: header-bearer
  exclude_paths: []
  target_url: https://meshi-bucket.s3.amazonaws.com/openapi.json
  type: api
deployment:
  environments:
  - staging
plan_items:
  item-api-security:
    deployment:
      configuration:
      - zap-stg-api
      tags:
      - staging
      trigger: deployment
resource_management:
  runner_config:
    job_setup_timeout_minutes: 40
    job_execution_timeout_minutes: 40
    # pr_job_setup_timeout_minutes: 40
    # pr_job_execution_timeout_minutes: 40
#   exclude:
#     plan_items:
#       item-code-vulnerability:
#         resources:
#           - name: demo-for-tests
#             type: repo
